import React from 'react'
import styles from '../styles/calculator.module.css'
import { useState } from 'react';
import Head from 'next/head';


const calculator = () => {
    const op:string[] = ['/','*','+','-'];
    const [item , setItem] = useState<string>("")
    const [calculate, setCalculate] = useState<string>("")
    const onChange = ((e:any)=>{
        if (op.includes(e) && item === '' || op.includes(e) && op.includes(item.slice(-1))) {
            return;
        }
        setItem(item + e);
        if (!op.includes(e)) {
            setCalculate(eval(item + e).toString())
        }
               
    })
    const cal = (()=>{

            setItem(eval(item).toString())
        
    })
    const Delete = (()=>{
        setItem("");
    })
    const butn:number[] = [9,8,7,6,5,4,3,2,1,0];
    const butnArray = butn.map((e:number,indx:number) => {
        return <button className={styles.singlebtn} onClick={() => {onChange(e.toString())}}>{e}</button>        
    })
    

  return (<>
  <Head>
        <title>Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <h1 className={styles.heading}>It's Owais Sheikh Calculator</h1>
    <div className={styles.container}>
        <div className={styles.box}>
            <input type="text" value={item} onChange={onChange}/>
        </div>
        <div className={styles.btn}>
            {butnArray}
            <button className={styles.singlebtn} onClick={() => {onChange("/")}}>/</button>
            <button className={styles.singlebtn} onClick={() => {onChange("*")}}>*</button>
            <button className={styles.singlebtn} onClick={() => {onChange("+")}}>+</button>
            <button className={styles.singlebtn} onClick={() => {onChange("-")}}>-</button>
            <button className={styles.singlebtn} onClick={Delete}>C</button>
            <button className={styles.singlebtn} onClick={cal}>=</button>
        </div>
    </div></>
  )
}

export default calculator