import Head from 'next/head'
import styles from '../styles/Home.module.css'
import React, { useState } from 'react';

export default function Home() {
  const [name, setName] = useState<string>("");
  const [submit, setSubmit] = useState<string[]>([]);
  const Change = ((e:any) => {
    e.preventDefault();
    setName(e.target.value);
    
  })
  const Click = ((e:any) => {
      e.preventDefault();
      setSubmit([name,...submit]);
      setName("");
  })
  const Delete = ((e:any) => {
      var updatedArr = submit.filter(item => submit.indexOf(e) != submit.indexOf(item))     
      setSubmit(updatedArr);
  })
  const DeleteAll = ((e:any) => {
     setSubmit([]);
  })
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <label htmlFor="input">User Input</label>
      <input type="text" id='input' value={name} onChange = {Change} />
      <button onClick = {Click}>Submit</button>  
      <div>
        {
          submit.length >= 1 ? submit.map((item:any, idx:number) => {
              return <p key={idx}>{item} <button onClick={(e) => {e.preventDefault(); Delete(item) }}>Delete</button></p>
          }): ""}
          <button onClick={DeleteAll}>Delete All</button>

      </div>
    </div>
  )
}
